name: learn-github-actions
run-name: Introduction to Github actions
on: [push]
jobs:
  my_first_job:
    name: My first job
  my_second_job:
    name: My second job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo hello world!